# Use an official Python runtime as a parent image
FROM python:3.6-slim
RUN apt-get update
RUN apt-get -y install r-base
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
#RUN pip install -r requirements.txt
#RUN pip install numpy
#RUN pip install scipy
#RUN pip install scikit-learn
# Make port 80 available to the world outside this container
#EXPOSE 80

# Define environment variable
ENV NAME World
#ENTRYPOINT ["script.sh"]
#CMD[]
# Run app.py when the container launches
#CMD ["python", "app.py"]
CMD["sh","format.sh"]
CMD ["sh", "script.sh"]
